-- Auto-generated from schema-map-postgres.yaml (map@sha1:8C4F2BC1C4D22EE71E27B5A7968C71E32D8D884D)
-- engine: postgres
-- table:  webauthn_challenges

CREATE TABLE IF NOT EXISTS webauthn_challenges (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  rp_id VARCHAR(255) NOT NULL,
  challenge_hash CHAR(64) NOT NULL,
  metadata JSONB NOT NULL,
  expires_at TIMESTAMPTZ(6) NOT NULL,
  created_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  CONSTRAINT ux_webauthn_challenge UNIQUE (rp_id, challenge_hash)
);
